# Config for PandaCtrlInterface

!include ../cfg/redis_nuc.yaml

panda:
  # taken from franka-panda/examples/opspace/python/opspace_control.py
  #np.array([0., -np.pi/6., 0., -5./6. * np.pi, 0., 2./3. * np.pi, 0.])
  neutral_joint_angles: [0.0, -0.524, 0.0, -2.617, 0.0, 2.094, 0.1]

controller:
  selected_type: 'EEImpedance' # Choose between 'EEImpedance', 'JointVelocity'
  Real:
    EEImpedance:
      kp:  [100, 100, 100, 60.0, 60.0, 60.0] #70 #50 #200 #75 #200 # P Gain for Impedance Control
      kv: [20.0, 20.0, 20.0, 10.0, 10.0, 10.0]
      damping: 1.0 #1 #0.5 #1 #0.5 # Damping factor [0,1]
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0