# Cfg file for  Demo control environment
world:
  type: 'Real' #'Bullet'
  robot: 'sawyer' #'panda'
data_dir: 'data'
# Simulation parameters
sim_params:
  time_step: 0.004166  # in seconds #0.004166 #0.002 #0.004166  # 1./240.
  MAX_STEPS: 500
real_params:
  nuc_hostname: "c3po-ctrl.stanford.edu" # Hostname for the NUC for real robot control.

redis:
  host: c3po-ctrl.stanford.edu
  port: 6379
  password: "/home/robot/redis_pw.txt"

# redis:
#   host: localhost
#   port: 6379

#policy_freq : 10 # Hz
policy_freq: 20 # For gazebo?
control_freq: 500 # Hz
!include ../../cfg/sawyer.yaml
!include ../../cfg/panda.yaml
!include ../../cfg/table_and_bin.yaml
scene_objects:
  'None'
goal_position:
  lower:
    [0.3, -0.2, 0.0]  # CHANGED
  upper:
    [0.5, 0.5, 0.2]   # CHANGED

sensor:
  camera:
    name:
        'camera'
    image:
      height: 224
      width: 224
    extrinsics:
        eye_position:
          [0.6, 0.0, 1.0]
        target_position:
          [0.6, 0., 0]
        up_vector:
          [1., 0., 1.]
    intrinsics:
        image_height: 1080
        image_width: 1920
        fov: 60
        near_plane: 0.02
        far_plane: 100
    # Parameters for randomization
    random:
      randomize: False
      extrinsics:
        eye_position:
          lower:
            [0.6, 0., 1.75]
          upper:
            [0.6, 0., 1.75]
        target_position:
          lower:
            [0.6, 0., 0]
          upper:
            [0.6, 0., 0]
      intrinsics:
        fov:
          lower: 50
          upper: 80
        near_plane:
          lower: 0.01
          upper: 0.05
        far_plane:
          lower: 10
          upper: 150

controller:
  selected_type: 'JointTorque' # Choose between 'EEImpedance', 'JointVelocity'
  Bullet:
    EEImpedance:
      kp: [65.0, 65.0, 65.0, 10., 10., 10.] #70 #50 #200 #75 #200 # P Gain for Impedance Control
      damping: 1.0 #1 #0.5 #1 #0.5 # Damping factor [0,1]
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
    JointVelocity:
      kv: 2.0 #0.5
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0 #1.0
      output_min: -1.0 #-1.0
    JointImpedance:
      kp: 250 #100
      damping: 1.0
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
    JointTorque:
      input_max: 1.0
      input_min: -1.0
      output_max: 5.0
      output_min: -5.0
    EEPosture:
      kp: 80 #70 #50 #200 #75 #200 # P Gain for Impedance Control
      damping: 1.0 #1 #0.5 #1 #0.5 # Damping factor [0,1]
      posture_gain: 60
      posture: [0,-1.18,0.00,2.18,0.00,0.57,3.3161]
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
  Real:
    EEImpedance:
      kp:  [40, 40, 40, 5.0, 5.0, 3.0] #70 #50 #200 #75 #200 # P Gain for Impedance Control
      kv: [10.0, 10.0, 10.0, 1.0, 1.0, 1.7]
      damping: 1.0 #1 #0.5 #1 #0.5 # Damping factor [0,1]
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
    JointVelocity:
      kv: 10.0 #0.5
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0 #1.0
      output_min: -1.0 #-1.0
    JointImpedance:
      kp: [20.0, 40.0, 20.0, 40.0, 10.0, 12.0, 4.0] #[70.0, 70.0, 60.0, 60.0, 50.0, 50.0, 20.0] #[100.0, 100.0, 80.0, 80.0, 70.0, 70.0, 50.0]
      kv: [2.0, 3.0, 2.0, 2.0, 2.0, 2.0, 0.2]
      damping: 1.0
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
    JointTorque:
      input_max: 1.0
      input_min: -1.0
      output_max: 5.0
      output_min: -5.0
    EEPosture:
      kp:  [40, 40, 40, 5.0, 5.0, 3.0] #70 #50 #200 #75 #200 # P Gain for Impedance Control
      kv: [10.0, 10.0, 10.0, 1.0, 1.0, 1.7]
      damping: 1.0 #1 #0.5 #1 #0.5 # Damping factor [0,1]
      posture_gain: [5.0, 5.0, 5.0, 4.0, 3.0, 3.0, 3.0]  #[7.0, 7.0, 7.0, 6.0, 5.0, 5.0, 5.0] #0.7
      input_max: 1.0
      input_min: -1.0
      output_max: 1.0
      output_min: -1.0
  interpolator_pos:
      type: 'linear'
      order: 1
      max_dx: 0.2
      ramp_ratio: 0.2
  interpolator_ori:
      type: 'linear'
      fraction: 0.2
    # max_dx: 0.01
    # ramp_ratio: 0.2

object:
  'None'
  # object_dict:
  #   # To add objects via arenas, list them directly using
  #   # key object_%i,
  #   object_0:
  #     name: '013_apple'
  #     path:
  #       'objects/ycb/013_apple/google_16k/textured.urdf'
  #     pose: [[1.5, 0, 0], [0,0,0]]
  #     is_static: True
  #     default_position: [0.7, 0.1, 0.03] #z  = 0.1
  #   object_1:
  #     name: '006_mustard_bottle'
  #     path:
  #       'objects/ycb/006_mustard_bottle/google_16k/textured.urdf'
  #     pose: [[0, 0, 0], [0, 0, 0]]
  #     is_static: False
  #     default_position: [0.2, 0.1, 0.03]

  # random:
  #   randomize: True
  #   position:
  #     lower:
  #       [0.3, -0.2, 0.1]
  #     upper:
  #       [0.7, 0.2, 0.1]

# Perception and Learning
env:
  observation_space:
    low:
      [-2.0, -2.0, -2.0]
    high:
      [2.0, 2.0, 2.0]
  action_space:
    low: [-0.2, -0.2, -0.2]
    high: [0.2, 0.2, 0.2]

learning_parms:
  hyperparameters:
  learning_rate:


vision_params:
  segmentation:
